### PR TITLE
Update checkout + node actions in workflows, use .nvmrc + caching

### PR DESCRIPTION
**Pull request by thelovekesh**
## Type of Change

- Workflows

### What should this PR do?
- This PR will help workflows to resolve the node version from `.nvmrc` file instead of the engines prop from `package.json`.

### What are the acceptance criteria?
- Check if workflows are resolving node version which is defined in the nvm config file.

### CODE REVIEW

**Comment by thelovekesh** [comment]
@MattIPv4 Please do a review when time permits. 

Thanks.

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 This seems to remove [the ability for us to load a specific NPM version](https://github.com/actions/setup-node/issues/529), which is exactly why these pipelines are currently set to use the engines prop, so we can set both Node & NPM versions the same way.

**Comment by thelovekesh** [comment]
@MattIPv4 By default nvm resolves the same npm version which is shipped with a particular node binary in this case `v16.16.0`.
When `nvm install && nvm use` command is executed in the project root it automatically resolves the `npm v8.11.0`.

image

Please note the resolved npm version here, which is the same as defined in the package's engines prop, so IMHO resolving the npm version explicitly is overkill here.

Please LMK if there are any other questions.

**Comment by MattIPv4** [comment]
We specifically define the NPM version here as we've run into issues in the past where we need to bump NPM beyond what is normally shipped. The change you are proposing removes the ability, I see that as a regression in the functionality of these workflows.

**Comment by MattIPv4** [comment]
I'm all for bumping the checkout action and using the newer Node.js action that has caching built-in, but let's stick to defining the versions for Node.js & NPM from engines, so they're exactly what we define them to be.

**Comment by thelovekesh** [comment]
@MattIPv4 Just asking out of curiosity, are you sure the current CI install npm command works correctly?

In the CI the command executed for installing npm echoed something like `npm i -g npm@"^8.11.0"` which does not establish the desired npm version correctly. 

image


image

**Comment by thelovekesh** [comment]
@MattIPv4 Please check now. I have added a step with a guard to check and update the NPM version according to package engines.npm version.

**Comment by MattIPv4** [comment]
Oh interesting, maybe this has been silently failing for a while. It definitely worked at one point in the past 'cause we had to bump NPM to get dependencies installing correctly

**Review by MattIPv4 — APPROVED** [review]
LGTM

**Pull request merged**
