### PR TITLE
Syntax Highlighting for Docker and Yaml

### LINKED ISSUE #176: Add syntax highlighting for docker/docker-compose
### Feature description

We have global options to enable Dockerfile and docker-compose.yaml -- we should provide correct syntax highlighting for these files when present.

We should make the syntax highlighting for these async so that the Prism data is generated in a separate bundle file and is present in the main bundle, being loaded only when needed.

### How the feature is useful

Correct syntax highlighting for the Dockerfile & YAML docker-compose file.

### PR DESCRIPTION
**Pull request by aihowes**
## Type of Change
Implements dynamic components for Docker and Yaml Prism syntax highlighting.

I've also changed the limit of chunks allowed, this was necessary to allow the lazyloading of the Docker and Yaml Prism plugin and components. 

There was a note on the chunk limit that it was necessary for easy embedding. If this chunk limit gets implemented the PR still works - the components just won't lazyloaded.

Currently ESlint also errors due to the dynamic import. Importing and using `parser: "babel-eslint",` in `parserOptions` fixes this. Let me know if you would like another commit with this change. 

## What issue does this relate to?
Fixes #176 

### What should this PR do?
Implements Docker and Yaml Prism components for docker-composer and Dockerfile.
It also allows new prism components to be created an implemented.

### What are the acceptance criteria?
Check if removing the chunk limit is OK for embedding. 
Check ESlint issue

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Lgtm in terms of functionality.

Please could you remove `LimitChunkCountPlugin` as a dependency completely now that we're not using it, and the fix for eslint would be best in this PR, as this is what needs it.

**Comment by aihowes** [comment]
Changes done but actions were cancelled?

**Comment by MattIPv4** [comment]
Looks like GitHub was having some issues, just retriggered the runs

**Review by MattIPv4 — APPROVED** [review]
Lgtm!

**Comment by aihowes** [comment]
@MattIPv4 thanks!

**Pull request merged**
