### PR TITLE
Fix index.html fallback

### PR DESCRIPTION
**Pull request by jordy758**
If an index.html was added to a root of a directory it would not show without adding /index.html after it, the fallback options do not work. This fixes that issue.

### CODE REVIEW

**Comment by MattIPv4** [comment]
👋 Do you have a minimal config share link that reproduces this issue? Right below where you've made your change is dedicated routing logic that should handle the fallbacks correctly

**Comment by jordy758** [comment]
> 👋 Do you have a minimal config share link that reproduces this issue? Right below where you've made your change is dedicated routing logic that should handle the fallbacks correctly

Sure, with just this https://www.digitalocean.com/community/tools/nginx?domains.0.routing.fallbackHtml=true&domains.0.routing.fallbackPhp=false it already does not do what its supposed to do. Just try deploying it on some web server and just add an index.html, it won't work.

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
So after some poking to better understand the actual issue at hand, it seems that with the current behaviour of NGINXConfig, the fallback setting only fails if you attempt to access a directory that exists (which `/` does). If you attempt to access say `/missing` or `/missing/` the fallback works as expected.

This PR doesn't seem to fix the behaviour in the correct way though, as it changes the config such that `/missing/` would prefer to route to `/missing/index.html`, not the current expected behaviour of always using `/index.html`.

This presents two issues to me:

1. The routing behaviour of fallback has changed, no longer always using the root index, but the index of the current directory.
2. If a directory exists without an `index.html` file inside it, the fallback routing still does not work and you get the same 403 as before.

Is there a way this can be refined so that we fix this bug of accessing directories that exist, but always routing back to `/index.html` per the current fallback behaviour, rather than changing the behaviour?

**Comment by jordy758** [comment]
> This PR doesn't seem to fix the behaviour in the correct way though, as it changes the config such that `/missing/` would prefer to route to `/missing/index.html`, not the current expected behaviour of always using `/index.html`.

When I read the options I thought this was what it's supposed to do. If you have a folder inside the root dir and you go to ```domain.td/folder1/``` I'd expect it to check if an index.php or index.html (if you enable the fallback route) is present instead of having to specify ````domain.td/folder1/index.html```to see the contents of de index.html file.

> If a directory exists without an index.html file inside it, the fallback routing still does not work and you get the same 403 as before.

This actually is a second issue that indeed occurs and also needs fixing.

**Comment by Gattuso11** [comment]
> > This PR doesn't seem to fix the behaviour in the correct way though, as it changes the config such that `/missing/` would prefer to route to `/missing/index.html`, not the current expected behaviour of always using `/index.html`.
> 
> When I read the options I thought this was what it's supposed to do. If you have a folder inside the root dir and you go to ```domain.td/folder1/``` I'd expect it to check if an index.php or index.html (if you enable the fallback route) is present instead of having to specify ````domain.td/folder1/index.html```to see the contents of de index.html file.
> 
> > If a directory exists without an index.html file inside it, the fallback routing still does not work and you get the same 403 as before.
> 
> This actually is a second issue that indeed occurs and also needs fixing.

Check cluserver on Instagram

**Comment by Gattuso11** [comment]
Good

**Comment by kelvinkessy** [comment]
> If an index.html was added to a root of a directory it would not show without adding /index.html after it, the fallback options do not work. This fixes that issue.
> 

Npo It can't show that en the options are all working well juxt the code had got errors it should be checked again to make sure where error arises

**Comment by MattIPv4** [comment]
Going to close this out as the PR appears to be stale, with the issues highlighted previously still unresolved.

**Pull request closed without merging**
