### PR TITLE
adds resolvers

### PR DESCRIPTION
**Pull request by mathieu-aubin**
adds popular Quad9 and Verisign resolvers, disabled by default
fixes some tabulations here and there to align stuff using tabs=8 chars
adds a space for pid

### CODE REVIEW

**Comment by mathieu-aubin** [comment]
i kinda like the project, it's got limitations yes but it allows many to run a decent server without too much hassle, at least on debian and related.

Speaking of debian... have you thought about having an option for non debian-based distributions (no sites-available/enabled folders on most if not all other distribs, user set to 'nginx'.. etc)

Just a thought, thanks.

**Comment by rollsappletree** [comment]
> Speaking of debian... have you thought about having an option for non debian-based distributions (no sites-available/enabled folders on most if not all other distribs, user set to 'nginx'.. etc)

This would be fantastic.
I use your fantastic service on AWS with AmazonLinux2 images and I have to always make a lot of changes etc. Would be fantastic to have the possibility to choose between Debian derivates or Centos derivates...

**Comment by MattIPv4** [comment]
Hey there @mathieu-aubin,

Thanks a ton for this sweet PR! 😄

We've recently started work on a full rewrite of the tool in the `master` branch, which has resulted in this PR being rather out-of-date -- I've included these changes in a commit directly on the branch, so this PR can now be closed.

However, would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Comment by mathieu-aubin** [comment]
@MattIPv4 mail sent

**Pull request closed without merging**
