### PR TITLE
Adding Laravel-specific rules

### PR DESCRIPTION
**Pull request by moniang**
## Type of Change
Add Laravel Nginx Conf.

What issue does this relate to?
N/A

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 Tyvm for this.

This has brought up an interesting issue with our current design:

image

To fix this, could you update the following:

https://github.com/digitalocean/nginxconfig.io/blob/4cfdcdb8d1c2df185e9ba437ca9c79e7c2ef17e8/src/nginxconfig/scss/_panel.scss#L36-L45

🔽

```scss
    .header-group,
    .buttons-group {
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
    }

    .header-group {
      justify-content: space-between;

      h3 {
```

(moving `justify-content: space-between;` into the `.header-group` selector)

**Comment by moniang** [comment]
This rule can be implemented through index.php fallback....

**Comment by MattIPv4** [comment]
@moniang if this can be implemented through the PHP fallback that the tool already ahs, we should add the preset button and have it enable that. Not everyone may be aware that is the configuration needed for Laravel, so the button is still an improved user experience.

**Comment by Atiladanvi** [comment]
@MattIPv4 
It would be nice if this can open again. I have some specifics configs for server work correctly for a laravel application and In addition to that I can inject nginx steroids too.

**Comment by MattIPv4** [comment]
@Atiladanvi you'll need to create a new PR if you want to contribute Laravel preset or Laravel specific rules :)

**Comment by Atiladanvi** [comment]
@MattIPv4 There we go again! :laughing:

**Pull request closed without merging**
